#import <Cocoa/Cocoa.h>

NSColor *ATARAXIA_CUSTOM_RED_01();
NSColor *ATARAXIA_CUSTOM_BLUE_01();
NSColor *ATARAXIA_CUSTOM_GREEN_01();
NSColor *ATARAXIA_CUSTOM_YELLOW_01();
NSColor *ATARAXIA_CUSTOM_ORANGE_01();
NSColor *ATARAXIA_CUSTOM_PURPLE_01();
NSColor *ATARAXIA_CUSTOM_PINK_01();
