#ifdef __OBJC__
#import <Cocoa/Cocoa.h>
#endif

#ifdef __OBJC__
NSColor *ATARAXIA_CUSTOM_RED_01();
NSColor *ATARAXIA_CUSTOM_BLUE_01();
NSColor *ATARAXIA_CUSTOM_GREEN_01();
NSColor *ATARAXIA_CUSTOM_YELLOW_01();
NSColor *ATARAXIA_CUSTOM_ORANGE_01();
NSColor *ATARAXIA_CUSTOM_PURPLE_01();
NSColor *ATARAXIA_CUSTOM_PINK_01();
#else
void *ATARAXIA_CUSTOM_RED_01();
void *ATARAXIA_CUSTOM_BLUE_01();
void *ATARAXIA_CUSTOM_GREEN_01();
void *ATARAXIA_CUSTOM_GREEN_01();
void *ATARAXIA_CUSTOM_YELLOW_01();
void *ATARAXIA_CUSTOM_ORANGE_01();
void *ATARAXIA_CUSTOM_PURPLE_01();
void *ATARAXIA_CUSTOM_PINK_01();
#endif
